console.log("Hellow world!")
console.log("commit verified")
console.log("second commit is verifed now on profile")
console.log("made changes on the UI")
console.log("MADE CHANGES TO THE BACKEND")
console.log("BOTH BACKEND AND UI WORKING VERIFIED")